### ISSUE TITLE
Pylint and sonar-scanner doesn't count character with the same way

### ISSUE THREAD

**Issue by usinelogicielle** [omegacen/pylint-sonarjson#10] opened 2023-01-18 15:10 UTC
I found another problem between pylint and sonar-scanner.
Pylint use ast module to count UTF8 character. Specially the endColumn of Pylint.
https://docs.python.org/3.8/library/ast.html#ast.AST.end_col_offset 
In the documentation, the count is done with byte offset and not character offset. So if the code contains accent from other language. The accent character is size 2 and not 1. Then sonar-scanner crash because the endColumn position doesn't contains code.

I don't know how to handle this problem. Except maybe create a new parameters to not add endColumn in the json report.
What do you think?

I write an issue in pylint github with an example : https://github.com/PyCQA/pylint/issues/8072 
But pylint team closed the issue because only use ast module.

**Comment by LvffY** [comment] 2023-01-19 21:18
I don't know if this plugin should handle the case. In my case, the issue came from my `__init__.py` files that were all empty.

Because of that, I think that Pylint or Sonarqube had integration issues with empty files. 

In my case, I had following line in my `pylintrc` file : 

```ini
ignore-patterns=__init__.py
```

**Comment by teake** [comment] 2023-01-20 08:27
This is a duplicate of https://github.com/omegacen/pylint-sonarjson/issues/6, which was closed. So I'm closing this as well. Sorry, I know this can be a bit frustrating, but I think the time and energy is better spend in fixing the upstream bug in `ast` than in implementing a workaround here.

**Closed as completed by teake** 2023-01-20 08:27 UTC
